services:
  backend:
    build: ./backend
    container_name: audio-transcriber-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: audio-transcriber-frontend
    ports:
      - "3000:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend-test:
    build: ./backend
    command: pytest
    volumes:
      - ./backend:/app

  frontend-test:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm test -- --watchAll=false
    environment:
      - CI=true